define(['/AliceSPA/AliceSPA.module.js'],function(module){
    module.constant('AliceSPAConfig',{
        'Protocol':'http',
        'ServerHost':'localhost',
        'ServerPort':'8080',
        'ClientHost':'localhost',
        'ClientPort':'8081',
        'ApiPath':'/api'
    })
});
