define([
    '/AliceSPA/AngularExt.js',
    '/AliceSPA/AliceSPA.module.js',
    '/AliceSPA/Constant/Config.constant.js',
    '/AliceSPA/Service/Account.service.js',
    '/AliceSPA/Service/APIProtocol.service.js',
    '/AliceSPA/Service/Data.service.js',
    '/AliceSPA/Service/Error.service.js',
    '/AliceSPA/Service/Notifier.service.js',
    '/AliceSPA/Service/Config.service.js',
    '/AliceSPA/Service/Captcha.service.js',
    '/AliceSPA/Service/DirectiveHandle.service.js',
    '/AliceSPA/Service/Session.service.js',
    '/AliceSPA/Service/DirectDatabase.service.js',
    '/AliceSPA/Directive/ImageCaptcha.directive.js'
    ],
    function(){
        console.log('Alice SPA Loaded.',AliceSPA);
    });
